project_id = "lpdjtzwfxsjjudhxinmk"

[functions.send-otp]
verify_jwt = false

[functions.admin-user-management]
verify_jwt = false

[functions.export-job-url]
verify_jwt = false

[functions.queue-integrity-check]
verify_jwt = false

[functions.track-request-proxy]
verify_jwt = false

[functions.submit-donation]
verify_jwt = false

[functions.submit-aid-request]
verify_jwt = false

[functions.submission-status]
verify_jwt = false

[functions.precheck-aid-submission]
verify_jwt = false

[functions.upload-id-doc]
verify_jwt = false
