/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as RequestRouteImport } from './routes/request'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminScoringRouteImport } from './routes/admin.scoring'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminReferencesRouteImport } from './routes/admin.references'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminPublicSettingsRouteImport } from './routes/admin.public-settings'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminDistributionRouteImport } from './routes/admin.distribution'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScoringRoute = AdminScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferencesRoute = AdminReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicSettingsRoute = AdminPublicSettingsRouteImport.update({
  id: '/public-settings',
  path: '/public-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistributionRoute = AdminDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/request': typeof RequestRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/distribution': typeof AdminDistributionRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/public-settings': typeof AdminPublicSettingsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/scoring': typeof AdminScoringRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/request': typeof RequestRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/distribution': typeof AdminDistributionRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/public-settings': typeof AdminPublicSettingsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/scoring': typeof AdminScoringRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/request': typeof RequestRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/distribution': typeof AdminDistributionRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/public-settings': typeof AdminPublicSettingsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/admin/scoring': typeof AdminScoringRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/donate'
    | '/request'
    | '/track'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/distribution'
    | '/admin/donations'
    | '/admin/public-settings'
    | '/admin/queue'
    | '/admin/references'
    | '/admin/requests'
    | '/admin/scoring'
    | '/admin/users'
    | '/admin/'
    | '/admin/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/donate'
    | '/request'
    | '/track'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/distribution'
    | '/admin/donations'
    | '/admin/public-settings'
    | '/admin/queue'
    | '/admin/references'
    | '/admin/requests'
    | '/admin/scoring'
    | '/admin/users'
    | '/admin'
    | '/admin/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/donate'
    | '/request'
    | '/track'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/distribution'
    | '/admin/donations'
    | '/admin/public-settings'
    | '/admin/queue'
    | '/admin/references'
    | '/admin/requests'
    | '/admin/scoring'
    | '/admin/users'
    | '/admin/'
    | '/admin/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DonateRoute: typeof DonateRoute
  RequestRoute: typeof RequestRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scoring': {
      id: '/admin/scoring'
      path: '/scoring'
      fullPath: '/admin/scoring'
      preLoaderRoute: typeof AdminScoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/references': {
      id: '/admin/references'
      path: '/references'
      fullPath: '/admin/references'
      preLoaderRoute: typeof AdminReferencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/public-settings': {
      id: '/admin/public-settings'
      path: '/public-settings'
      fullPath: '/admin/public-settings'
      preLoaderRoute: typeof AdminPublicSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distribution': {
      id: '/admin/distribution'
      path: '/distribution'
      fullPath: '/admin/distribution'
      preLoaderRoute: typeof AdminDistributionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRequestsRoute
    }
  }
}

interface AdminRequestsRouteChildren {
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
}

const AdminRequestsRouteChildren: AdminRequestsRouteChildren = {
  AdminRequestsIdRoute: AdminRequestsIdRoute,
}

const AdminRequestsRouteWithChildren = AdminRequestsRoute._addFileChildren(
  AdminRequestsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDistributionRoute: typeof AdminDistributionRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminPublicSettingsRoute: typeof AdminPublicSettingsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminReferencesRoute: typeof AdminReferencesRoute
  AdminRequestsRoute: typeof AdminRequestsRouteWithChildren
  AdminScoringRoute: typeof AdminScoringRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDistributionRoute: AdminDistributionRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminPublicSettingsRoute: AdminPublicSettingsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminReferencesRoute: AdminReferencesRoute,
  AdminRequestsRoute: AdminRequestsRouteWithChildren,
  AdminScoringRoute: AdminScoringRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DonateRoute: DonateRoute,
  RequestRoute: RequestRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
